[Feature/#6 feat basket] 구매하기_장바구니 화면
DO-SOPT-CDS-APP-7/Kurly-AOS pull request #10
Opened 2023-11-27 12:16 UTC by chanubc

## 🎀 Related Issues
#### close #6 

## 🤔 What Did You Do
- [ ] mvvm 패턴 적용
- [ ] 프로그레스 인디케이터 및 애니메이션 구현
- [ ] constraint chain 및 동적 비율 코딩
- [ ] 무료배송 금액 구현
- [ ] bottomSheetDialog theme round 18dp 및 background 색상 적용

## 📸 screenShot

https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/assets/106955456/fbc04246-3d6f-4d41-b657-e613b41e8687

2023-11-28 04:04 UTC, stellar-halo requested changes
로직 깔끔해서 좋습니다! 고생하셨어요 🙂👍🏻 몇가지 수정 사항만 봐주세요~

2023-11-28 04:04 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val count = MutableLiveData<Int>().apply { value = 1 }
초기값을 이렇게 부여한 이유가 있을까요?

2023-11-28 04:04 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val freePrice: MutableLiveData<Int> = _freePrice
Mutable로 되어 있네요!

2023-11-28 04:04 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:id="@+id/img_purchase_item"
iv입니다!

2023-11-28 04:04 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:text="베테랑의 대표 메뉴를 집에서"
이건 공통 text이기도 하고 서버가 내려주면 서버에서 받아오면 될 것 같은데 제 기억엔 아마 안줬던 것 같아요. 제가 string 빼둔 게 있으니 나중에 바꾸면 될 것 같습니다~

2023-11-28 16:15 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val count = MutableLiveData<Int>().apply { value = 1 }
이전 pr에서 선언과 동시에 초기화를 하시면 좋을것 같다는 피드백을 받아서요!
또 count는 최소 1이 되게끔 해놓았습니다

2023-11-28 16:17 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val freePrice: MutableLiveData<Int> = _freePrice
LiveData로 수정하면 될까요? liveData 와 MutableLiveData의 차이를 모르고 작성한거라..

2023-11-28 16:43 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val count = MutableLiveData<Int>().apply { value = 1 }
아하! 그럴 땐 그냥
`MutableLiveData<Int>(1) `
이렇게 괄호 안에 넣어주면 초기값 설정 됩니다!

2023-11-28 16:44 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val freePrice: MutableLiveData<Int> = _freePrice
맞습니다! Mutable과 LiveData를 쓰는 이유는 코틀린의 장점인 불변성을 지켜주기 위함입니다!
Mutable은 val임에도 불구하고 값을 변경시켜줄 수가 있는데, 참조하고 있는 객체는 같기 때문입니다.
LiveData는 읽기 위해서만 쓰이고
Mutable은 객제 값을 변경할 때 쓰입니다!
그래서 Mutable은 private이고(viewModel에서만 쓰여야 하니까요)
LiveData는 public인 것입니다 ^_^

2023-11-28 16:54 UTC, chanubc commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:id="@+id/img_purchase_item"
[1e1b19c](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/10/commits/1e1b19c0e74f82fb3bb6be985b4d8f0de6de3a17) 수정했습니다!

2023-11-28 16:56 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val freePrice: MutableLiveData<Int> = _freePrice
좋은 답변 감사합니다! 그런 이유가 있는줄 모르고 막 가져다 썼네요^^
[44a2c4b](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/10/commits/44a2c4b56e4ed28677128eaf3491495a430ccf33) 수정완료했습니다. 확인해 주세요

2023-11-30 17:08 UTC, stellar-halo approved these changes
고생하쎳습니다 멋쟁이~

2023-12-01 04:57 UTC, pump9918 approved these changes
장바구니 화면 고생많았습니다!!

2023-12-01 04:57 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +    val count = MutableLiveData<Int>(1)
훨씬 간결하네요!

2023-12-01 04:57 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/util/extensions/AnimateProgressBar.kt
> +package com.example.chicoryaos.util.extensions
애니메이션이 이렇게 쓰는거였구만... 잘 배워갑니다

2023-12-01 05:37 UTC, merged