[Feature/#14] 서버 통신
DO-SOPT-CDS-APP-7/Kurly-AOS pull request #17
Opened 2023-11-29 19:20 UTC by chanubc

## 🎀 Related Issues
#### close #14 

## 🤔 What Did You Do
- [ ] coil bindingAdapter 구현
- [ ] 구매하기 화면 서버 데이터 화면 연결
- [ ] 구매하기_장바구니 화면 서버 get 통신, 코루틴 사용
- [ ] 구매하기_주문서 화면 서버 데이터 화면 연결

## 📸 screenShot
https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/assets/106955456/cfcffaf7-43d0-4d5a-a639-4f41b0068908

## 🤔  To Reviewrs
커밋을 더 쪼갰어야 됫는데 신경을 못썼네요
-,+ 버튼 로직을 detailViewModel로 옮길지 고민입니다. 뷰모델이 2개가 겹치네요..

2023-11-30 17:38 UTC, stellar-halo requested changes
빠른 작업 속도 고생했어요! 😁👍

2023-11-30 17:38 UTC, stellar-halo commented on app/build.gradle
> +    implementation 'io.coil-kt:coil-svg:2.4.0'
coil까지 쓰는 당신 멋있어요

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
세로 방향만 되는 portrait가 설정이 안되었네요!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/data/AuthService.kt
> +    suspend fun getRelatedProduct(
오 코루틴~

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/model/ResponseRelatedProductDTO.kt
> +    val status: String,
동일하다고 해도 @SerialName을 붙여주는 것이 좋다고 하네요! 직렬화 과정에서 오류가 발생할 가능성을 줄여준다고 합니다.

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    private val detailViewModel by viewModels<DetailViewModel>()
아하 이런 문제가 생겼군요. 하나의 viewModel을 공유하도록 바꾸는 것도 좋은 방안이 될 것 같습니다.

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    )
^_^ viewModel에 있어야 할 친구 같습니다!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +                binding.ivBasketImg.load(it.imageURL)
binding Adapter를 쓰는데 이렇게 직접 load해줘야 하는 이유가 있을까요?

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    }
마찬가지로 viewModel에 있어야 할 로직같습니다~

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    }
이 친구도 그래 보입니다!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        binding.tvMiddleTitle.text = it.productName
databinding을 쓰고 있으니 코틀린 파일에서 직접 값을 대입하지 않아도 됩니다!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +            kotlin.runCatching {
kotlin.runCatching이 아니라 runCatching으로만 써줘도 됩니다!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +            }
```suggestion
            }.onFailure { throwable ->
                Log.d("server fail", "$throwable")
            }
```

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +                    _product.value = it.body()!!.data
!! 연산자는 앱이 터질 위험이 있어 좋지 않다고 합니다.

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +                }
이렇게 분기 처리를 해준 이유가 무엇일까요?

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/receipt/PurchaseReceiptViewModel.kt
> +    val count = MutableLiveData<Int>(1)
private이 아닌 이유가 무엇인가요? 외부에서 값을 변경하게 되면 위험합니다!

2023-11-30 17:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/util/binding/BindingAdapter.kt
> +    }
좋습니다~

2023-11-30 20:21 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/receipt/PurchaseReceiptViewModel.kt
> +    val count = MutableLiveData<Int>(1)
[49f6344](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/17/commits/49f63444b5ff264b0d7a99e22addc51f2ec7fdc4) 수정 했습니다!

2023-11-30 20:21 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        binding.tvMiddleTitle.text = it.productName
[f07e777](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/17/commits/f07e77775b2376267d2d56e4ac080c545132f184) 수정완료!

2023-11-30 20:22 UTC, chanubc commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
[71482ac](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/17/commits/71482ac308c43b7b55427af32c6719395d7d9e24) 수정했습니당

2023-11-30 20:22 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/model/ResponseRelatedProductDTO.kt
> +    val status: String,
헉 귀찮아서 안썼는데 그러한 문제가 있었군요! 써야 되겠네요..

2023-11-30 20:25 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    private val detailViewModel by viewModels<DetailViewModel>()
DetailViewModel 여기에 엄청 많은 로직이 들어 갈것 같아 일단은 분리해서 작업했습니다! 
DetailViewModel 뷰모델에서 서버연결 3개,  +,- 버튼 로직, 할인 계산 까지 해야해서 일단은 분리 해서 했는데, 작업 하면서도 하나로 하는게 더 빠르겠다는 생각을 하긴 했어요. 
한 뷰모델을 크게 쓰는 편인가요? 아니면 최대한 쪼개 쓰는 편인가요?

viewmodel에서 서버 통신과 mvvm패턴을 이번에 처음 사용해 봐서 어떠한 식으로 로직을 짜는지 잘 모르겠습니다!

2023-11-30 20:26 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +                binding.ivBasketImg.load(it.imageURL)
[40351cd](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/17/commits/40351cdb72ca7c6c595fd13492ab73efc3483b7e) 수정했습니ㅏ

2023-12-01 03:45 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseBasketFragment.kt
> +    private val detailViewModel by viewModels<DetailViewModel>()
저도 최근에 그것땜에 참,,,고민중인데요
원래는 쪼개 쓰는 편이었는데, 최근에 그것에 대해서 코드리뷰를 받은 적이 있어서요!
조금 다른 상황이지만 밑에 블로그를 한 번 참조하시고, 액티비티와 프래그먼트 간의 뷰모델도 한 번 고민해보세요! 어떤 것이 정답이다는 없으니까요.
https://zion830.tistory.com/72

서로 다른 scope에서 ViewModel을 공유하는 것은 ViewModel의 기본 사용 원칙에 어긋나는 안티 패턴에 해당된다.<< 라고는 하니, 지금 상황에서 viewModel을 공유하는 것은 좋지 않아 보입니다!

Fragment간에 데이터를 전달하거나 viewModel을 통합하는 것이 더 낫지 않을까 싶어요!

- Fragment Result API를 사용하여 Data 전달
- Fragment간 공통의 ViewModel(ex. HostActivity의 ViewModel)로 전달
- Jetpack의 Navigation에서 제공하는 safe-args로 전달
- 
https://velog.io/@sysout-achieve/Android-Fragment%EA%B0%84-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EB%8B%AC-%EB%B0%A9%EB%B2%95%EB%93%A4
참고해보셔요!

2023-12-01 04:29 UTC, stellar-halo approved these changes
짱짱! 최고예요. 항상 날카로운 질문 좋습니다. 저도 많이 배워가요~

2023-12-01 04:37 UTC, pump9918 approved these changes
고생 많으셨어요!!

2023-12-01 04:37 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/model/ResponseRelatedProductDTO.kt
> +    val data: List<Data>,
List<Data>가 여러 데이터를 한번에 표기하는 방법이군요!

2023-12-01 04:37 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/data/AuthService.kt
> +        @Query("page") page: Int,
제가 아는거랑 좀 다른가 했더니 Query까지 야무지게 챙기셨네요! 잘 참고했습니닿ㅎ

2023-12-01 08:20 UTC, merged