Feature/#3 feat purchase
DO-SOPT-CDS-APP-7/Kurly-AOS pull request #5
Opened 2023-11-22 14:33 UTC by chanubc

## 🎀 Related Issues
#### close #3 

## 🤔 What Did You Do
- [ ] bottom sheet fragment 생성
- [ ] ui 작성
- [ ] viewmodel 생성
- [ ] dataBinding
- [ ] price formatter 추가

## 📸 screenShot

https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/assets/106955456/52773d35-238f-4bc2-832a-49e3401f09a4

## 🤔 To Reviewer
- dataBinding을 처음 해봐서 알맞게 했는지 모르겠습니다. 코드리뷰 부탁드려요!
- 페이지 단위로 개발할 생각이고 제가 맡은 플로우에 첫 페이지에 해당합니다.
- 1번 bottom sheet이 생기고 1번 bottom sheet의 구매하기 버튼을 누르면 다음 bottom sheet으로 넘어가는데, fragment에서 fragment를 호출을 할지, view를 2개 겹쳐 gone, visible을 할지 고민입니다..

2023-11-23 05:30 UTC, stellar-halo requested changes
고생하셨어요! 뚝딱 만들어내셨네요 짱짱 최고 👍
다만 xml에서 id 컨벤션이 지켜지지 않았네요! 확인해주세요 😊

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/detail/DetailActivity.kt
> +            purchaseBottomSheet.show(supportFragmentManager, PurchaseFragment.TAG)
👍

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        super.onDestroyView()
순서가 반대로 된 것 같습니다!

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        const val TAG = "BottomSheetPurchase"
어떤 TAG인지 조금 더 상세하게 드러나면 좋을 것 같습니다~

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +        count.value = 1
여기서 초기화가 아닌 8번째 줄에서 변수 선언할 때 같이 초기화해도 좋을 것 같아요!

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +        calculatePrice()
변수와 함수가 이름이 동일하네요! 혹시 조금 다르게 하시는 건 어떤가요?

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/util/extensions/PriceFormatter.kt
> +            return DecimalFormat("#,###").format(price)
👍

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:id="@+id/mv_drag_handle"
저희 id convention [component]_[view]_[description] 입니다!!

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:text="[전주 베테랑] 칼국수"
나중에 서버 통신할 때 간단하게 바꿀 수 있게 item data class 를 하나 만들고 viewModel에 해당 객체를 만들어둔 뒤, 미리 xml에 연결을 다 해두면 후에 서버 연결하기 편합니다!

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:text="@{viewModel.calculatePrice + '원'}"
string.xml과 함께 출력할 수 있습니다! 원을 string으로 뽑아주세요

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:text="@{viewModel.calculatePrice + '원'}"
😀

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +                    android:onClick="@{()->viewModel.countDecrease()}"
야무지네요!👍

2023-11-23 05:30 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +
두 줄 enter 되어 있네요! 한 줄 삭제해주세요

2023-11-23 10:53 UTC, pump9918 approved these changes
고생 많으셨습니다~

2023-11-23 10:53 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/util/extensions/PriceFormatter.kt
formatter는 어떤 기능을 하는건가요??

2023-11-23 12:24 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        super.onDestroyView()
_binding=null을 먼저 처리해주면 더 안정성 있게 메모리를 해제할 수 있다고 합니다.

-라고 앞선 과제들에서 코드리뷰 받았습니다!

2023-11-23 13:29 UTC, chanubc commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:text="@{viewModel.calculatePrice + '원'}"
수정했습니다~

2023-11-23 13:32 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/util/extensions/PriceFormatter.kt
1000원으로 출력되는 가격을
1,000원 3개씩 끊어서 , 를 출력해 줍니다!

2023-11-23 13:45 UTC, chanubc commented on app/src/main/res/layout/bottom_sheet_fragment_purchase.xml
> +            android:id="@+id/mv_drag_handle"
수정했습니다!

2023-11-23 13:47 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +        calculatePrice()
수정완료 했습니당

2023-11-25 03:39 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseFragment.kt
> +        super.onDestroyView()
제가 거꾸로 알고 있었나보네요..머쓱😅

2023-11-27 12:05 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/purchase/PurchaseViewModel.kt
> +        count.value = 1
[6ac479f](https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/pull/5/commits/6ac479fa76cb9ba51ed16adb5a6244c520ea8294) 수정했습니다!

2023-11-28 04:07 UTC, stellar-halo approved these changes
고생하셨습니다~😊
다만 아직 xml id와 string 부분이 덜 지켜진 것 같습니다!
시간이 나실 때 수정해주시면 감사하겠습니다~~

2023-11-28 07:00 UTC, merged