Feature/#4 찜하기 Bottom Sheet
DO-SOPT-CDS-APP-7/Kurly-AOS pull request #7
Opened 2023-11-26 10:04 UTC by pump9918

## 🎀 Related Issues
#### close #issueNumber

## 🤔 What Did You Do
- [] bottom sheet fragment 생성
- [] ui 작성
- [] 가상데이터 넣기

## 📸 screenShot

https://github.com/DO-SOPT-CDS-APP-7/Kurly-AOS/assets/125239880/e56dff69-abaf-47ee-95e6-4e50c0e3f02e

## To Reviewer
- viewModel을 어떤식으로 써야할지 잘 모르겠어서 조언 부탁드립니다ㅜ
- 다른 고객이 함께본 상품, 함께 구매하면 좋은 상품으로 나눠야하지만, 가상데이터로는 같은 값을 넣어놨습니다
- Bottom sheet를 끝까지 끌어올리면 위에 round가 사라지는 이슈가 있는데 어떻게 해결하면 좋을까요??
- RecyclerView로 상품을 불러왔는데 피그마와 규격이 좀 다른 느낌.. 조언 부탁드립니다ㅜ
- 돈의 단위는 피드백 후 viewModel 작성 시 추가하겠습니다

2023-11-26 11:38 UTC, stellar-halo requested changes
viewModel같은 경우에는 이번 세미나 과제이기도 하니, 한 번 차근 차근 읽어보면서 적용해보세요! 
data는 전부 viewModel에서 다룬다고 생각하시면 될 것 같습니다. 
비슷한 동작을 @chanubc 님 pr에서 많이 볼 수 있을 것 같습니다. 한 번 참고 해보세요!

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        app:strokeWidth="0dp" />
직접 bar부분을 만드셨군요!! 다음 번에는 디자이너에게 esset으로 뽑아서 사용해도 되냐고 물어봐도 괜찮을 듯 해요~~ (요것도 괜찮음)

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +    app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">
혹시 직접 style이랑 배경 정의해서 적용시켜줘도 그럴까요?
https://notepad96.tistory.com/170
참고해보세요!

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        android:layout_width="wrap_content"
wrap이 아니라 match_parent로 해보시겠어요?

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/res/layout/item_bookmark_product.xml
> +        app:layout_constraintTop_toBottomOf="@id/iv_item_wish_list_keep" />
색상이 빠진 거 같습니다!

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/res/drawable/dummy_1.png
나중에 서버에서 이미지 받아오게 되면 삭제해주세요! 😁

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/Bookmark.kt
ui가 아닌 data 패키지(폴더)에 넣어주세요!

2023-11-26 11:38 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/BookmarkFragment.kt
> +        get() = requireNotNull(_binding)
뷰바인딩 좋습니다! 제가 빼둔 Util 한 번 써보시는 건 어떤가요~?

2023-11-27 01:29 UTC, chanubc commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        app:strokeWidth="0dp" />
전 sgv나 png형태로 추출하는 것보다 가능하다면 코드로 작성하는 것이 가장 좋다고 생각합니다!
https://developer.android.com/studio/write/vector-asset-studio?hl=ko

1. svg로 추출 : 벡터 드로어블을 처음 로드할 때는 같은 래스터 이미지보다 CPU 사이클이 더 많이 소모될 수 있습니다. 
2. png로 추출 : 1x 로 추출시에는 화질이 깨지고, 3x이상 추출하게 되면 용량이 너무 늘어남.

전 코드로 작성 가능 하다면 최대한 코드로 작성하는 편입니다!

2023-11-27 02:33 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/BookmarkFragment.kt
> +        get() = requireNotNull(_binding)
BottomSheetDialogFragment()를 상속 받는  fragment에서도 동일하게 사용 가능한가요?

2023-11-27 02:57 UTC, chanubc approved these changes
고생하셨습니다!

리사이클러뷰의 좌우 padding을 25dp로 주고 item의 margin도 추가로 주었기 때문에 피그마랑 맞지는 않습니다!
1. item decoration을 사용하거나
2. constaint를 활용하여 3개를 비율코딩 하는 방식이 있습니다. (이 부분은 제가 작성했으니 pr올리면 참고하시면 좋을것 같아요!)
3. 현재로써 가장 좋은 방법은 reycelerview의 padding은 현재 그대로 두고 item 에 적용된 margin만 marginEnd = 11dp 이런식으로 적용하는 것이 좋을듯 합니다!

2023-11-27 02:57 UTC, chanubc commented on app/src/main/res/drawable/ku_dummy.jpg
ㅋㅋㅋㅋㅋㅋㅋ여기 아무도 못나간...

2023-11-27 02:57 UTC, chanubc commented on app/src/main/res/values/colors.xml
> +    <color name="ku_light_gray_drag_handler">#DDDDDD</color>
제거랑 겹치는 몇가지 부분 merge할때 충돌날 거 같은데 일단 한번 해봅시다!ㅋㅋㅋ

2023-11-27 02:57 UTC, chanubc commented on app/src/main/res/values/themes.xml
> +    </style>
대략 봤을때 요거 2개가 충돌 날거 같아요! (누구거 부터 머지하지?ㅋㅋㅋ)
나중에 하는 사람이 pull 받고 conflict해결하고 다시 push하면 될것 같긴 해요

2023-11-27 02:57 UTC, chanubc commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        android:paddingEnd="25dp"
**1. 이렇게 될 경우 스크롤 영역이 좌우로 25dp 만큼 줄게 됩니다!**
리사이클러뷰의 스크롤 영역을 침범하지 않으면서 첫번째 item만 padding을 주려면 item decoration을 사용하면 됩니다!
(물론 지금 화면은 3개만 유지 되기 때문에 상관 없습니다)

**2. 리사이클러뷰 사용시 좌측정렬**
+추가로 지금 형태로 하면 item이 좌측부터 차례로 쌓이는 형태이기 때문에 커다란 기종일 수록 가운데 정렬되는 것이 아닌, 좌측 정렬 되는 형태로 보일 것 같습니다! 
나중에 시간이 남는다면 3개만 있으므로 리사이클러뷰가 아닌 constraint로 비율 코딩하는 식으로 마만드는게 좋을것 같아요! 
(이번 합동세미나에서는 굳이 상관없다 생각합니다)

2023-11-27 02:57 UTC, chanubc commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/BookmarkViewHolder.kt
> +    }
중요한 부분은 아니지만 scope함수 with(binding) { } 으로
한번에 묶어서 사용할 수도 있습니다!

```suggestion
    fun onBind(bookmarkData: Bookmark) {
    with(binding) {
 ivItemWishList.setImageResource(bookmarkData.productImage)
        tvItemWishListTitle.text = bookmarkData.productTitle
        tvItemSalePrice.text = bookmarkData.productPrice.toString()
        }
    }
```

2023-11-27 10:09 UTC, stellar-halo commented on app/src/main/res/values/themes.xml
> +    </style>
먼저 작업 다 끝낸 사람 것부터 merge하고 그 이후에 pull 받고 처리하면 될 것 같아요!

2023-11-27 10:10 UTC, stellar-halo commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/BookmarkFragment.kt
> +        get() = requireNotNull(_binding)
제가 고 부분을 놓쳤는데 찬우님이랑 호연님이 동일하게 쓰는 부분이니 그 부분은 또 따로 util로 빼면 될 것 같네요!

2023-11-28 05:53 UTC, pump9918 commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +    app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior">
와우 해결됐습니다! 체고의 해결사...

2023-11-28 06:02 UTC, pump9918 commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        android:layout_width="wrap_content"
좌측 paddin에 맞춰서 잘 나오게는 됐습니다 :)
근데 휴대폰 크기에 따라 왼쪽에 쏠리는 현상이 있는데...
어케 해결하는 좋을지 고민중

2023-11-28 06:05 UTC, pump9918 commented on app/src/main/res/layout/item_bookmark_product.xml
> +        app:layout_constraintTop_toBottomOf="@id/iv_item_wish_list_keep" />
세밀한 포인트 감사합니다!

2023-11-28 06:06 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/Bookmark.kt
충돌날 수 있을 거 같아서 서버 초기세팅 이후 옮겨놓겠습니다 :)

2023-11-28 14:02 UTC, pump9918 commented on app/src/main/res/values/colors.xml
> +    <color name="ku_light_gray_drag_handler">#DDDDDD</color>
충돌 방지하려고 중복 코드 부분 삭제 후 커밋했습니당

2023-11-28 14:02 UTC, pump9918 commented on app/src/main/res/values/themes.xml
> +    </style>
충돌 방지하려고 중복 코드 부분 삭제 후 커밋했습니당

2023-11-30 04:36 UTC, pump9918 commented on app/src/main/res/layout/bottom_sheet_fragment_bookmark.xml
> +        android:paddingEnd="25dp"
이번 합세에서는 constraint를 사용하는걸로...

2023-11-30 04:37 UTC, pump9918 commented on app/src/main/java/com/example/chicoryaos/ui/bookmark/BookmarkViewHolder.kt
> +    }
오호 좋은 팁 감사합니다!!

2023-12-01 08:51 UTC, pump9918 commented
하나로 묶어서 올렸습니다

2023-12-01 08:51 UTC, closed without merging